/*
 * Copyright 2010 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.dkmp

import com.dkmp.model.Praca;


rule "Validate Praca OK"
no-loop true
    salience 10
    when
        praca : Praca(listaProponowanychRecenzentow.size() == 3)
    then
        modify( praca ) { setPracaOk ( true ) }
        modify( praca ) { setPracaValidationError ( null ) }
end

rule "Validate Praca NOT OK"
no-loop true
	salience 10
    when
        praca : Praca(listaProponowanychRecenzentow.size() != 3)
    then
        modify( praca ) { setPracaOk ( false ) }
        modify( praca ) { setPracaValidationError ( "Nalezy wybrac 3 recenzentow" ) }
end


